site_name: 泛世界语
site_url: http://www.pandunia.info/putonghan
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../putonghan
site_dir: ../../html/putonghan
theme: cerulean
nav:
    - Home: 'index.md'
    - '字母表': abc.md
    - '短语集': fraze.md
    - '词典': pandunia-cini.md
    - '语源': leksaslia.md

