site_name: Pandunia
site_url: http://www.pandunia.info/france
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../france
site_dir: ../../html/france
theme: readthedocs
plugins:
    - search:
        lang: fr
nav:
    - Accueil: 'index.md'
    - 'Info':
        - 'Présentation': dunia_baxe.md
        - 'Principes de fonctionnement': filsofe.md
        - 'Questions et réponses': eske_i_jawabe.md
        - 'Traduire ce site': tarja_netoloke.md
    - 'Grammaire':
        - 100_baze_kanun.md
        - 101_dunia_loga.md
        - 102_ABC.md
        - 104_viceloga.md
        - 105_namloga.md
        - 106_nomer.md
        - 107_modeloga.md
        - 108_ateloga.md
        - 109_jumla.md
        - 110_logabina.md
    - 'Leçons':
        - 'Phrases courantes': fraze.md
        - 'Leçons': darse.md
    - 'Vocabulaire':
        - 'Pandunia → français': pandunia-france.md
        - 'Français → pandunia': france-pandunia.md
        - 'Etymologie': leksaslia.md
        - 'Recherche': tiddly.html
    - 'Grammaire': kanun.md

