site_name: Pandunia
site_url: http://www.pandunia.info/english
repo_url: https://github.com/barumau/pandunia/
site_author: Risto Kupsala
docs_dir: ../../english
site_dir: ../../html/english
theme: readthedocs
nav:
    - Home: 'index.md'
    - 'Info':
        - 'Introduction': dunia_baxe.md
        - 'Principles': filsof.md
    - 'Grammar and Rules':
        - 'The basic rules': 100_baze_kanun.md
        - 'World words': 101_dunia_loga.md
        - 'Spelling and pronunciation': 102_ABC.md
        - 'Word classes': 103_logotipe.md
        - 'Pronouns': 104_viceloga.md
        - 'Nouns': 105_namloga.md
        - 'Numerals': 106_numbe.md
        - 'Modifiers': 107_modeloga.md
        - 'Verbs': 108_ateloga.md
        - 'Sentences': 109_jumla.md
        - 'Word building': 110_logabina.md
    - 'Lessons':
        - 'Basic Phrases': fraze.md
        - 'Course': darse.md
    - 'Words':
        - 'Pandunia-English': pandunia-english.md
        - 'English-Pandunia': english-pandunia.md
        - 'Origins of words': leksaslia.md
        - 'Search': tiddly.html
    - 'Appendix':
        - History: 401_historia.md
        - 'Questions & Answers': eske_i_jawabe.md
        - 'Translate this site': tarja_netoloke.md

