site_name: Pandunia
site_url: http://www.pandunia.info/english
repo_url: https://github.com/barumau/pandunia/
site_author: Risto Kupsala
docs_dir: ../../english
site_dir: ../../html/english
theme: readthedocs
nav:
    - Home: 'index.md'
    - 'Info':
        - 'Introduction': 001_dunia_basha.md
        - 'Principles': 002_filsofi.md
    - 'Grammar and Rules':
#        - 'The basic rules': 100_baze_kanun.md
        - 'World words': 101_dunia_loga.md
        - 'Spelling and pronunciation': 102_ABC.md
        - 'Word classes': 103_logatipe.md
        - 'Mini Pandunia grammar' : mini_pandunia.md
        - 'Midi Pandunia grammar' : medi_pandunia.md
        - 'Maxi Pandunia grammar' : maxi_pandunia.md
#        - 'Pronouns': 104_viseloga.md
#        - 'Nouns': 105_namloga.md
#        - 'Numerals': 106_nomer.md
#        - 'Modifiers': 107_modeloga.md
#        - 'Verbs': 108_karmaloga.md
#        - 'Sentences': 109_jumla_bina.md
        - 'Word building': 110_loga_bina.md
    - 'Lessons':
        - 'Basic Phrases': 200_baze_jumla.md
        - 'Course': 201_shula.md
    - 'Words':
        - 'Pandunia-English': pandunia-english.md
        - 'English-Pandunia': english-pandunia.md
        - 'Origins of words': leksaslia.md
        - 'Search': tiddly.html
    - 'Appendix':
        - History: 401_histori.md
        - 'Questions & Answers': 402_sual_e_javabu.md
        - 'Adapting foreign words' : 403_loga_hapu.md
        - 'Translate this site': tarja_netoloke.md

