site_name: Pandunia
site_url: http://www.pandunia.info/pandunia
repo_url: https://github.com/barumau/pandunia/
site_author: Risto Kupsala
docs_dir: ../../pandunia
site_dir: ../../html/pandunia
use_directory_urls: false
theme:
  name: material
  logo: logo.png
  favicon: favicon.png
extra_css:
  - stile.css
nav:
    - ABC: abc.md
    - kata:
        - "da let baru's pate dante": baru_dante.md
        - 'tri behe e un gui': 3_buze_e_guye.md
        - 'tri lit goro': 3_lil_gurube.md
    - kitab:
        - "homan's putong hak": putong_hake.md
        - 'din kitab': dini_kitabe.md
    - 'lexe liste':
        - 'lexe buk': https://www.pandunia.info/panlexia/
        - 'gogia se nam': desha_nam.md
        - 'lexaslia': leksaslia.md
        - 'lexe se num': lexi_nume.md
        - rang: rang.md
    - filme: filme.md
    - linke: linke.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/pandunia/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jf5GHcHXKk
    - icon: fontawesome/brands/facebook
      link: http://www.facebook.com/groups/pandunia
    - icon: fontawesome/brands/telegram
      link: https://t.me/joinchat/AAAAAENlKqzlMtGkrmf5rg
markdown_extensions:
  - toc:
      toc_depth: 2
