site_name: Pandunia
site_url: http://www.pandunia.info/pandunia
repo_url: https://github.com/barumau/pandunia/
site_author: Risto Kupsala
docs_dir: ../../pandunia
site_dir: ../../html/pandunia
theme: readthedocs
nav:
    - ABC: abc.md
    - sage:
        - 'lili urse du tungi dante': urse_dante.md
        - 'tin buze e guye': 3_buze_e_guye.md
        - 'tin lili gurube': 3_lil_gurube.md
    - kitabe:
        - 'insan du putongi hake': putong_hake.md
        - 'dini kitabe': dini_kitabe.md
    - logoliste:
        - 'logia': logia.html
        - 'desha nam': desha_nam.md
        - 'logaslia': leksaslia.md
        - 'loga di numbe': loga_di_numbe.md
    - filme: filme.md
    - linke: linke.md

