site_name: Pandunia
site_url: http://www.pandunia.info/pandunia
repo_url: https://github.com/barumau/pandunia/
site_author: Risto Kupsala
docs_dir: ../../pandunia
site_dir: ../../html/pandunia
theme: material
nav:
    - ABC: abc.md
    - kata:
        - 'la shau baru su pati dante': baru_dante.md
        - 'tri behe e un gui': 3_buze_e_guye.md
        - 'tri shau goro': 3_lil_gurube.md
    - kitabu:
        - 'insan su putong haki': putong_hake.md
        - 'din kitabu': dini_kitabe.md
    - 'loga liste':
        - 'lexibuku': logia.html
        - 'dexa su nam': desha_nam.md
        - 'lexi asal': leksaslia.md
        - 'lexi su nume': lexi_nume.md
    - filme: filme.md
    - linke: linke.md
extra:
  social:
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/pandunia/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jf5GHcHXKk
    - icon: fontawesome/brands/facebook
      link: http://www.facebook.com/groups/pandunia
    - icon: fontawesome/brands/telegram
      link: https://t.me/joinchat/AAAAAENlKqzlMtGkrmf5rg

