site_name: Pandunia
site_url: http://www.pandunia.info/pandunia
repo_url: https://github.com/barumau/pandunia/
site_author: Risto Kupsala
docs_dir: ../../pandunia
site_dir: ../../html/pandunia
theme: readthedocs
nav:
    - ABC: abc.md
    - kata:
        - 'la lili baru su pasi dante': urse_dante.md
        - 'tri behe e un gui': 3_buze_e_guye.md
        - 'tri lili goro': 3_lil_gurube.md
    - kitabu:
        - 'insan su putong haki': putong_hake.md
        - 'din kitabu': dini_kitabe.md
    - 'loga liste':
        - 'loga buku': logia.html
        - 'desha name': desha_nam.md
        - 'loga asal': leksaslia.md
        - 'loga su nomer': loga_di_numbe.md
    - filme: filme.md
    - linke: linke.md

