site_name: พันดูเนีย
site_url: http://www.pandunia.info/tai
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../tai
site_dir: ../../html/tai
theme: material
nav:
    - "พันดูเนีย": 'index.md'
extra:
  social:
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/pandunia/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jf5GHcHXKk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pandunia_
    - icon: fontawesome/brands/facebook
      link: http://www.facebook.com/groups/pandunia
    - icon: fontawesome/brands/telegram
      link: https://telegram.me/joinchat/Dhfgywdb7jonCD7DHCxuJw

