site_name: พันดูเนีย
site_url: http://www.pandunia.info/tai
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../tha
site_dir: ../../html/tha
use_directory_urls: false
theme:
  name: material
  language: th
  logo: logo.png
  favicon: favicon.png
  palette:
    primary: blue
  font:
    code: Ubuntu mono
nav:
    - "พันดูเนีย": 'index.md'
    - "พื้นฐาน": 'I-suma.md'
    - G-baze.md
    - pandunia-tha.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/pandunia/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jf5GHcHXKk
    - icon: fontawesome/brands/facebook
      link: http://www.facebook.com/groups/pandunia
    - icon: fontawesome/brands/telegram
      link: https://t.me/pandunia_grupe
markdown_extensions:
  - toc:
      toc_depth: 2
