site_name: Pandunia
site_url: http://www.pandunia.info/esperanto
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../esperanto
site_dir: ../../html/esperanto
theme: readthedocs
nav:
    - 'Ĉefpaĝo': 'index.md'
    - 'Bazaĵoj kaj strukturo de Pandunia':
        - 'Bazaj reguloj': 100_bazi_kanun.md
        - 'Tutmonda vortaro': 101_dunia_loge.md
        - 'Prononco': 102_ABC.md
        - 'Substantivoj': 104_namloge.md
        - 'Adjektivoj': 105_sifloge.md
        - 'Adverboj': 106_modologe.md
        - 'Numeraloj': 107_numloge.md
        - 'Pronomoj': 108_visloge.md
        - 'Verboj': 109_karloge.md
        - 'Vortfarado': 111_logobine.md
    - 'Lecionoj':
        - 'Utilaj frazoj': fraze.md
    - 'Vortaroj':
        - 'Pandunia-Esperanto': pandunia-esperanto.md
        - 'Esperanto-Pandunia': esperanto-pandunia.md
        - 'Etimologia vortaro': leksaslia.md

