site_name: Pandunia
site_url: http://www.pandunia.info/esperanto
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../esperanto
site_dir: ../../html/esperanto
theme: readthedocs
nav:
    - 'Ĉefpaĝo': 'index.md'
    - 'Bazaĵoj kaj strukturo de Pandunia':
        - 'Bazaj reguloj': 100_baze_kanun.md
        - 'Tutmonda vortaro': 101_dunia_loga.md
        - 'Prononco': 102_ABC.md
        - 'Pronomoj': 104_viseloga.md
        - 'Substantivoj': 105_nameloga.md
        - 'Nombrovortoj': 106_nomer.md
        - 'Modifaj vortoj': 107_modeloga.md
        - 'Verboj': 108_karmaloga.md
        - 'Vortfarado': 110_logabina.md
    - 'Lecionoj':
        - 'Utilaj frazoj': fraze.md
    - 'Vortaroj':
        - 'Pandunia-Esperanto': pandunia-esperanto.md
        - 'Esperanto-Pandunia': esperanto-pandunia.md
        - 'Etimologia vortaro': leksaslia.md

