site_name: lingua Pandunia
site_url: http://www.pandunia.info/ita
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../ita
site_dir: ../../html/ita
use_directory_urls: false
theme:
  name: material
  language: it
  logo: logo.png
  favicon: favicon.png
extra_css:
  - stile.css
nav:
    - 'Lingua ausiliaria globale': I01_ration.md
    - I02_filsofia.md
    - B02_nutshell.md
    - 'Regole basilari': B01_baze_kanun.md
    - 'Ortografia e pronuncia': G-ABC.md
    - 'Classi di parole': G-PoS.md
    - 'Pronomi': G-PRO.md
    - 'Sostantivi': G-N.md
    - 'Numerali': G-NUM.md
    - 'Modificatori': G-ADJ.md
    - 'Verbi': G-V.md
    - 'Vocabolario':
        - 'pandunia → italiano': pandunia-ita.md
        - 'italiano → pandunia': ita-pandunia.md
    - 'Da dove vengono le parole': L01_dunia_lexe.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/pandunia/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jf5GHcHXKk
    - icon: fontawesome/brands/facebook
      link: http://www.facebook.com/groups/pandunia
    - icon: fontawesome/brands/telegram
      link: https://t.me/pandunia_grupe
markdown_extensions:
  - toc:
      toc_depth: 2
