site_name: lingua Pandunia
site_url: http://www.pandunia.info/ita
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../ita
site_dir: ../../html/ita
use_directory_urls: false
theme:
  name: material
  language: it
  logo: logo.png
  favicon: favicon.png
  font:
    code: Ubuntu mono
nav:
    - 'Lingua ausiliaria globale': I01_ration.md
    - I02_filsofia.md
    - B02_nutshell.md
    - 'Regole basilari': B01_baze_kanun.md
    - 'Ortografia e pronuncia': G01_ABC.md
    - 'Classi di parole': G03_lexe_tipe.md
    - 'Pronomi': G07_vise_lexe.md
    - 'Sostantivi': G04_name.md
    - 'Numerali': G06_nume.md
    - 'Modificatori': G05_sifa.md
    - 'Verbi': G08_verbe.md
    - 'Da dove vengono le parole': L01_dunia_lexe.md
extra:
  social:
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/pandunia/
    - icon: fontawesome/brands/discord
      link: (https://discord.gg/CgZ6nUpj
    - icon: fontawesome/brands/facebook
      link: http://www.facebook.com/groups/pandunia
    - icon: fontawesome/brands/telegram
      link: https://t.me/pandunia_grupe
markdown_extensions:
  - toc:
      toc_depth: 2
