site_name: lingua Pandunia
site_url: http://www.pandunia.info/ita
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../ita
site_dir: ../../html/ita
use_directory_urls: false
theme:
  name: material
  language: it
  logo: logo.png
  favicon: favicon.png
  font:
    code: Ubuntu mono
nav:
    - 'Lingua ausiliaria globale': 001_ration.md
    - 002_filsofi.md
    - 003_baze.md
    - 'Regole basilari': 100_baze_kanun.md
    - 'Ortografia e pronuncia': 102_ABC.md
    - 'Classi di parole': 103_lexitipe.md
    - 'Pronomi': 104_viselexi.md
    - 'Sostantivi': 105_namlexi.md
    - 'Numerali': 106_nume.md
    - 'Modificatori': 107_modelexi.md
    - 'Verbi': 108_karlexi.md
    - 'Da dove vengono le parole': 101_dunia_lexi.md
extra:
  social:
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/pandunia/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jf5GHcHXKk
    - icon: fontawesome/brands/facebook
      link: http://www.facebook.com/groups/pandunia
    - icon: fontawesome/brands/telegram
      link: https://t.me/pandunia_grupe
markdown_extensions:
  - toc:
      toc_depth: 2
