site_name: Pandunian kieli
site_url: http://www.pandunia.info/fin
repo_url: https://github.com/barumau/pandunia/
site_author: Risto Kupsala
docs_dir: ../../fin
site_dir: ../../html/fin
use_directory_urls: false
theme:
  name: material
  language: fi
  logo: logo.png
  favicon: favicon.png
  palette:
    primary: blue
extra_css:
  - stile.css
plugins:
    - search:
        lang: fi
nav:
    - 'Johdanto': I-idea.md
    - 'Pandunian perusteet ja rakenne':
        - 'Perussäännöt': G-baze.md
        - 'Yleismaailmallinen sanasto': L-lexe.md
        - 'Ääntäminen': G-ABC.md
        - 'Sanaluokat': G-PoS.md
        - 'Pronominit': G-PRO.md
        - 'Substantiivit': G-N.md
        - 'Numeraalit': G-NUM.md
        - 'Määritteet': G-ADJ.md
        - 'Verbit': G-V.md
        - 'Prepositiot': G-PP.md
        - 'Lauserakenteet': G-P.md
        - 'Sanojen johtaminen': G-AFX.md
    - 'Oppitunteja':
        - 'Lauseita': K-fraze.md
        - 'Kurssi': K-kurse.md
    - 'Sanasto':
        - 'Pandunia-suomi': pandunia-fin.md
        - 'Suomi-pandunia': fin-pandunia.md
        - Sanahaku : https://www.pandunia.info/lexia/?d=fin
        - 'Alkuperäsanasto': lexaslia.md
    - 'Videoita': I-filme.md
    - Tietoa:
        - 'Historia': I-historia.md
        - 'UKK': FAQ.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/pandunia/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jf5GHcHXKk
    - icon: fontawesome/brands/facebook
      link: http://www.facebook.com/groups/pandunia
    - icon: fontawesome/brands/telegram
      link: https://t.me/pandunia_grupe
markdown_extensions:
  - toc:
      toc_depth: 2
